In [2]:
import requests
import base64
import pandas as pd
from typing import Dict, Any
from dotenv import load_dotenv
load_dotenv()
import os
import json
from typing import Dict, Any

In [8]:
def folder_to_df_merged(folder_path: str) -> Dict[str, pd.DataFrame]:
    result = {}

    for file in os.listdir(folder_path):
        if not file.endswith(".json"):
            continue

        path = os.path.join(folder_path, file)

        with open(path, encoding="utf-8") as f:
            data: Any = json.load(f)

        if isinstance(data, list) and all(isinstance(i, dict) for i in data):
            df = pd.json_normalize(data)

        elif isinstance(data, dict):
            list_keys = [k for k, v in data.items() if isinstance(v, list)]

            if list_keys:
                main_key = list_keys[0]
                df = pd.json_normalize(
                    data,
                    record_path=main_key,
                    meta=[k for k in data.keys() if k != main_key],
                    errors="ignore"
                )
            else:
                df = pd.DataFrame([data])

        else:
            df = pd.DataFrame()

        result[file.replace(".json", "")] = df
    
    return pd.concat(result.values(), ignore_index=True)

df = folder_to_df_merged("../data/raw")
df_result = df.explode("genres").dropna(subset=['genres'])

In [9]:
df_result = df

In [11]:
df_result = df_result.replace({'True': 1, 'False': 0})
df_result

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,user,artist_id,genres
2,2023-11-03T19:08:49Z,windows,114865,BR,200.185.254.31,Costa Rica (feat. The Kid LAROI) - Remix,Bankrol Hayden,Pain is Temporary,spotify:track:3tdjTdCCgKtwacsICCtPZZ,None,...,clickrow,trackdone,False,False,False,1.699038e+09,False,gigi,0Yr4BBpK2dkCp2UsrJ9LZN,melodic rap
4,2023-11-03T19:12:12Z,windows,90010,BR,191.23.42.158,Blueberry Faygo,Lil Mosey,Blueberry Faygo,spotify:track:6wJYhPfqk3KGhHRG76WzOh,None,...,playbtn,unexpected-exit,False,False,False,1.699039e+09,False,gigi,6Xgp2XMz1fhVYe7i6yNAax,melodic rap
5,2023-11-03T21:44:28Z,windows,159129,BR,191.23.42.158,Blueberry Faygo,Lil Mosey,Blueberry Faygo,spotify:track:6wJYhPfqk3KGhHRG76WzOh,None,...,appload,trackdone,False,False,False,1.699047e+09,False,gigi,6Xgp2XMz1fhVYe7i6yNAax,melodic rap
6,2023-11-03T21:47:12Z,windows,162546,BR,191.23.42.158,Blueberry Faygo,Lil Mosey,Blueberry Faygo,spotify:track:6wJYhPfqk3KGhHRG76WzOh,None,...,trackdone,trackdone,False,False,False,1.699048e+09,False,gigi,6Xgp2XMz1fhVYe7i6yNAax,melodic rap
7,2023-11-03T21:49:55Z,windows,162546,BR,191.23.42.158,Blueberry Faygo,Lil Mosey,Blueberry Faygo,spotify:track:6wJYhPfqk3KGhHRG76WzOh,None,...,trackdone,trackdone,False,False,False,1.699048e+09,False,gigi,6Xgp2XMz1fhVYe7i6yNAax,melodic rap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319635,2026-01-20T03:44:09Z,ios,0,BR,2804:14d:328c:56a8:804a:e6b5:cc3:18b5,You Make Me Feel So Young - Live At Royal Fest...,Frank Sinatra,You Make Me Feel So Young,spotify:track:6OQPeBd6CKouqH0Dsf1XkG,None,...,unknown,endplay,False,True,False,1.768881e+09,False,Fefo,1Mxqyy3pSjf8kZZL4QVxS0,swing music
319635,2026-01-20T03:44:09Z,ios,0,BR,2804:14d:328c:56a8:804a:e6b5:cc3:18b5,You Make Me Feel So Young - Live At Royal Fest...,Frank Sinatra,You Make Me Feel So Young,spotify:track:6OQPeBd6CKouqH0Dsf1XkG,None,...,unknown,endplay,False,True,False,1.768881e+09,False,Fefo,1Mxqyy3pSjf8kZZL4QVxS0,jazz
319635,2026-01-20T03:44:09Z,ios,0,BR,2804:14d:328c:56a8:804a:e6b5:cc3:18b5,You Make Me Feel So Young - Live At Royal Fest...,Frank Sinatra,You Make Me Feel So Young,spotify:track:6OQPeBd6CKouqH0Dsf1XkG,None,...,unknown,endplay,False,True,False,1.768881e+09,False,Fefo,1Mxqyy3pSjf8kZZL4QVxS0,vocal jazz
319639,2026-01-25T05:28:54Z,ios,0,BR,2804:38a:a09f:e5c5:3c84:35f8:2615:f6ba,Vou Deitar E Rolar (Quaquaraquaqua),Elis Regina,Vou Deitar E Rolar (Quaquaraquaqua),spotify:track:0GjOplhCphC5IF8ZHaXjbq,None,...,unknown,endplay,False,True,False,1.769319e+09,False,Fefo,7dnT2FUXhjirperXaH22IJ,mpb
319639,2026-01-25T05:28:54Z,ios,0,BR,2804:38a:a09f:e5c5:3c84:35f8:2615:f6ba,Vou Deitar E Rolar (Quaquaraquaqua),Elis Regina,Vou Deitar E Rolar (Quaquaraquaqua),spotify:track:0GjOplhCphC5IF8ZHaXjbq,None,...,unknown,endplay,False,True,False,1.769319e+09,False,Fefo,7dnT2FUXhjirperXaH22IJ,brazilian rock

In [12]:
df_result.columns

Index(['ts', 'platform', 'ms_played', 'conn_country', 'ip_addr',
       'master_metadata_track_name', 'master_metadata_album_artist_name',
       'master_metadata_album_album_name', 'spotify_track_uri', 'episode_name',
       'episode_show_name', 'spotify_episode_uri', 'audiobook_title',
       'audiobook_uri', 'audiobook_chapter_uri', 'audiobook_chapter_title',
       'reason_start', 'reason_end', 'shuffle', 'skipped', 'offline',
       'offline_timestamp', 'incognito_mode', 'user', 'artist_id',
       'genres'],
      dtype='object')

In [14]:
df_result = df_result.drop(columns = ['platform','conn_country', 'ip_addr','spotify_track_uri', 'episode_name',
       'episode_show_name', 'spotify_episode_uri', 'audiobook_title',
       'audiobook_uri', 'audiobook_chapter_uri', 'audiobook_chapter_title',"master_metadata_track_name", "master_metadata_album_artist_name", "master_metadata_album_album_name", "offline", "incognito_mode","offline_timestamp", "artist_id"])

In [15]:
df_result['ms_played'] = pd.to_numeric(df_result['ms_played'], errors='coerce')

In [87]:
pivot = (
    df_result
    .groupby(['genres', 'user'])
    .agg(
        sum_ms_played = pd.NamedAgg("ms_played","sum"),
        mean_ms_played = pd.NamedAgg("ms_played","mean"),
        skipped_percent = pd.NamedAgg("skipped","mean")
    )
)

In [88]:
pivot = pivot.unstack("user").fillna(0)
pivot.columns = [
    f"{pessoa}_{valor}" 
    for valor, pessoa in pivot.columns
]

In [89]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
x_scaled = scaler.fit_transform(pivot)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

def encontrar_cotovelo_kmeans(
    df,
    k_min=1,
    k_max=30,
    random_state=42
):

    X = df.copy()


    inertias = []
    k_range = range(k_min, k_max + 1)

    for k in k_range:
        model = KMeans(n_clusters=k, random_state=random_state, n_init="auto")
        model.fit(X)
        inertias.append(model.inertia_)

    x = np.array(list(k_range))
    y = np.array(inertias)

    p1 = np.array([x[0], y[0]])
    p2 = np.array([x[-1], y[-1]])

    distances = []
    for i in range(len(x)):
        p = np.array([x[i], y[i]])
        distance = np.abs(np.cross(p2 - p1, p1 - p)) / np.linalg.norm(p2 - p1)
        distances.append(distance)

    elbow_index = np.argmax(distances)
    k_otimo = x[elbow_index]

    return k_otimo

In [91]:
k_otimo = encontrar_cotovelo_kmeans(x_scaled)
print(k_otimo)
kmeans = KMeans(n_clusters=k_otimo, random_state=42)
pivot['cluster'] = kmeans.fit_predict(x_scaled)

17

C:\Users\matheuscury-ieg\AppData\Local\Temp\ipykernel_17108\829906701.py:34: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  distance = np.abs(np.cross(p2 - p1, p1 - p)) / np.linalg.norm(p2 - p1)

In [92]:
pivot

,Allanabre_sum_ms_played,Cury_sum_ms_played,Fefo_sum_ms_played,Gueguelas_sum_ms_played,gigi_sum_ms_played,Allanabre_mean_ms_played,Cury_mean_ms_played,Fefo_mean_ms_played,Gueguelas_mean_ms_played,gigi_mean_ms_played,Allanabre_skipped_percent,Cury_skipped_percent,Fefo_skipped_percent,Gueguelas_skipped_percent,gigi_skipped_percent,cluster
genres,,,,,,,,,,,,,,,,
acid jazz,0.0,2377166.0,0.0,0.0,0.0,0.000000,216106.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15
acid rock,0.0,0.0,48562.0,0.0,0.0,0.000000,0.000000,24281.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9
acid techno,0.0,0.0,0.0,215282.0,401230.0,0.000000,0.000000,0.000000,53820.500000,57318.571429,0.000000,0.000000,0.000000,0.750000,0.428571,0
acoustic pop,301836.0,0.0,79409.0,186320.0,0.0,150918.000000,0.000000,79409.000000,93160.000000,0.000000,0.500000,0.000000,1.000000,0.000000,0.000000,12
adult standards,4223668.0,10982.0,54382489.0,522269.0,11672.0,117324.111111,5491.000000,126470.904651,19343.296296,2918.000000,0.222222,0.500000,0.462791,0.111111,0.750000,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
west coast hip hop,437131.0,2043514.0,14323455.0,563289258.0,49734075.0,145710.333333,145965.285714,130213.227273,141458.879458,158894.808307,0.333333,0.285714,0.427273,0.256153,0.255591,6
witch house,2543988.0,197940.0,9141238.0,2459748.0,103346.0,158999.250000,197940.000000,103877.704545,64730.210526,12918.250000,0.125000,1.000000,0.090909,0.236842,0.875000,6
worship,465320.0,0.0,74680.0,1630.0,0.0,232660.000000,0.000000,18670.000000,543.333333,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,12
yacht rock,3352541.0,1006681.0,300930.0,38000.0,1440797.0,98604.147059,111853.444444,150465.000000,38000.000000,144079.700000,0.147059,0.666667,0.000000,0.000000,0.300000,6
zouk,0.0,0.0,126054.0,1018.0,255218.0,0.000000,0.000000,63027.000000,1018.000000,127609.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0

In [94]:
genero = input("Escolha um genero")

try:
    cluster = pivot.loc[[genero]]["cluster"][0]
    print("sugestoes:")
    generos_sugerids = pivot[pivot["cluster"] == cluster].index.tolist()

    for x in generos_sugerids:
        if x != genero:
            print(x) 
except:
    print("genero nao existe")

sugestoes:
acid techno
alté
ambient
anti-folk
banda
breakbeat
calypso
concerto
corrido
corridos bélicos
corridos tumbados
cumbia norteña
djent
finnish rock
freestyle
grupera
hardcore hip hop
hip house
japanese indie
lo-fi house
math rock
mathcore
melodic death metal
mexican rock
música mexicana
norteño
nz reggae
polka
ranchera
rockabilly
sad sierreño
sierreño
slowcore
tejano

C:\Users\matheuscury-ieg\AppData\Local\Temp\ipykernel_17108\600512222.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cluster = pivot.loc[[genero]]["cluster"][0]